server:
  port: 8200
spring:
  application:
    name: upload-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


mingrui:
  upload:
    path:
      windows: D:\\images
      linux: /wangxin/images
    img:
      host: http://81.70.211.185/
